FROM python:3.10-slim
WORKDIR /app

# install python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# install debian packages
RUN apt-get update && apt-get install -y ffmpeg

# run the application
CMD ["fastapi", "run", "--host", "0.0.0.0"]
