# prerequisites: nvidia gpu, nginx proxy manager

services:
  cctv-recanalyzer-api:
    build:
      context: ../cctv_recanalyzer
    expose:
      - 8000
    volumes:
      - ../cctv_recanalyzer:/app
      - ./data:/data
      - ./output:/output
    environment:
      - TZ=Asia/Seoul
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
    runtime: nvidia

  cctv-recanalyzer-webui:
    build:
      context: ../webui
    expose:
      - 80
    volumes:
      - ./output:/usr/share/nginx/html/static
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    depends_on:
      - cctv-recanalyzer-api

networks:
  default:
    external: true
    name: nginx-proxy-network
