FROM python:3.11

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN apt-get update

# Create the user and install sudo
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} --shell /bin/bash -m ${USERNAME} \
    && apt-get install -y sudo \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# Install dependencies
RUN apt-get install -y ffmpeg